services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "80"]
    restart: always

volumes:
  postgres_data:
