default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: feiravagas
  username: feiravagas
  password: feiravagas
  host: localhost
  port: 5432

test:
  <<: *default
  database: feira_vagas_test
 
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'].sub(/feira_vagas_production/, 'feira_vagas_production_cache') %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'].sub(/feira_vagas_production/, 'feira_vagas_production_queue') %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'].sub(/feira_vagas_production/, 'feira_vagas_production_cable') %>
    migrations_paths: db/cable_migrate
